# Generated by Django 5.0.3 on 2026-09-28 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description_short', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resumo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('DEVELOPMENT', 'Em Desenvolvimento'), ('WAITING_CLIENT', 'Aguardando Cliente'), ('READY', 'Pronto'), ('PUBLISHED', 'Publicado'), ('SOLD', 'Vendido'), ('MAINTENANCE', 'Em Manutenção'), ('OFFLINE', 'Offline'), ('PAUSED', 'Pausado'), ('CANCELLED', 'Cancelado'), ('ARCHIVED', 'Arquivado')], default='DEVELOPMENT', max_length=30, verbose_name='Status')),
                ('featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('public_visible', models.BooleanField(default=False, verbose_name='Público')),
                ('sold', models.BooleanField(default=False, verbose_name='Vendido')),
                ('sale_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Venda')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='Data de Venda')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pendente'), ('PARTIAL', 'Parcial'), ('PAID', 'Pago')], default='PENDING', max_length=20, verbose_name='Status de Pagamento')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('site_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL do Site')),
                ('staging_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL de Staging')),
                ('repository_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL do Repositório')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.category', verbose_name='Categoria')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='clients.client', verbose_name='Cliente')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='projects.technology', verbose_name='Tecnologias')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/', verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Legenda')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Capa')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Imagem do Projeto',
                'verbose_name_plural': 'Imagens do Projeto',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
