# Generated by Django 5.0.3 on 2026-09-28 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Domínio')),
                ('registrar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Registradora')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Data de Registro')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('EXPIRING', 'Expirando'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado'), ('UNKNOWN', 'Desconhecido')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Renovação Automática')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='clients.client', verbose_name='Cliente')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Domínio',
                'verbose_name_plural': 'Domínios',
                'ordering': ['expiration_date', 'domain'],
            },
        ),
    ]
