# Generated by Django 5.0.3 on 2026-09-28 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('provider', models.CharField(max_length=255, verbose_name='Provedor')),
                ('plan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Plano')),
                ('server', models.CharField(blank=True, max_length=255, null=True, verbose_name='Servidor (IP/Hostname)')),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Mensal Equivalente')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Mensal'), ('QUARTERLY', 'Trimestral'), ('SEMI_ANNUALLY', 'Semestral'), ('ANNUALLY', 'Anual'), ('BIENNIALLY', 'Bienal'), ('TRIENNIALLY', 'Trianual')], default='ANNUALLY', max_length=20, verbose_name='Ciclo de Faturamento')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('SUSPENDED', 'Suspensa'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosting_accounts', to='clients.client', verbose_name='Cliente')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosting_accounts', to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Conta de Hospedagem',
                'verbose_name_plural': 'Contas de Hospedagem',
                'ordering': ['expiration_date', 'provider'],
            },
        ),
    ]
