# Generated by Django 5.0.3 on 2026-09-28 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('monthly_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('next_billing_date', models.DateField(blank=True, null=True, verbose_name='Próxima Cobrança')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição/Escopo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_contracts', to='clients.client', verbose_name='Cliente')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_contracts', to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Contrato de Manutenção',
                'verbose_name_plural': 'Contratos de Manutenção',
                'ordering': ['next_billing_date'],
            },
        ),
    ]
